-- ============================================================================
-- Actions correctives — catalogue de libellés canon (comme document_etat pour
-- les motifs de refus de document), utilisé pour qualifier une irrégularité
-- constatée lors d'un contrôle. Chaque libellé cible les salariés, les
-- entreprises, ou les deux. Données réelles extraites du site legacy
-- (page=actions_correctives, 31 lignes).
-- ============================================================================

CREATE TABLE action_corrective (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nom TEXT NOT NULL,
    cible VARCHAR(30) NOT NULL CHECK (cible IN ('SALARIES', 'ENTREPRISES', 'SALARIES_ET_ENTREPRISES')),
    deleted_at TIMESTAMPTZ
);

INSERT INTO action_corrective (nom, cible) VALUES
    ('ACCORD D''ACCES', 'SALARIES'),
    ('ATTENTION / IMPORTANT : APRES TRAITEMENT DU RAPPORT - ENTREPRISE INDÉPENDANTE ET/OU SALARIE INCONNUE(S) PAR LE DONNEUR D''ORDRE', 'SALARIES_ET_ENTREPRISES'),
    ('ATTENTION / IMPORTANT : APRES TRAITEMENT DU RAPPORT - INFORMATION ERRONEE TRANSMISE PAR L''OUVRIER - DONNEUR D''ORDRE AVISE', 'SALARIES_ET_ENTREPRISES'),
    ('ATTENTION / IMPORTANT : AUCUN JUSTIFICATIF D’IDENTITÉ (Aucune pièce justificative d''identité telle que CNI, Titre de séjour, Passeport, Permis de Conduire, Carte BTP etc.)', 'SALARIES'),
    ('ATTENTION : SALARIE / OUVRIER DÉPART PRÉCIPITE DU CHANTIER LORS DE L’ARRIVÉE DU CONTRÔLEUR', 'SALARIES'),
    ('AVERTISSEMENT - CF. ETAT DES RELANCES DES REFUS D''ACCÈS EXPÉDIÉS AU(X) DONNEURS D''ORDRE', 'SALARIES_ET_ENTREPRISES'),
    ('CARTE ARTISANALE : ABSENCE DE PRESENTATION', 'SALARIES_ET_ENTREPRISES'),
    ('CARTE ARTISANALE NON VALIDE', 'SALARIES_ET_ENTREPRISES'),
    ('CARTE ARTISANALE VALIDE', 'SALARIES_ET_ENTREPRISES'),
    ('CLIENT – NON SOUMIS AU CONTROLE', 'ENTREPRISES'),
    ('CO - TRAITANT – NON SOUMIS AU CONTROLE', 'ENTREPRISES'),
    ('CREATION DOSSIER SALARIE', 'SALARIES'),
    ('DEMANDE D''AUTORISATION D''ACCORD DE SOUS-TRAITANCE AU DONNEUR D''ORDRE', 'ENTREPRISES'),
    ('DEMANDE DE COORDONNEES DE CONTACT AU DONNEUR D''ORDRE POUR TRAITEMENT NOUVEAU SALARIE', 'SALARIES'),
    ('DEMANDE DE PIECES ADMINISTRATIVES EXPEDIEE LE [voir état de relance]', 'SALARIES_ET_ENTREPRISES'),
    ('DOSSIER INCOMPLET - ABSENCE/EXPIRATION DE(S) PIECE(S) ADMINISTRATIVE(S)', 'SALARIES_ET_ENTREPRISES'),
    ('INTEGRATION DANS LA LISTE', 'SALARIES_ET_ENTREPRISES'),
    ('INTERDICTION DE TRAVAILLER (TITRE DE SEJOUR NON VALIDE, DETACHEMENT NON VALIDE, INAPTITUDE MEDICALE ETC..)', 'SALARIES'),
    ('INTERVENANT NON SOUMIS AU CONTROLE - AUTRE CHANTIER', 'SALARIES'),
    ('L''ENTREPRISE REFUSE DE SE SOUMETTRE AU CONTROLE MALGRE LES RELANCES EFFECTUEES', 'ENTREPRISES'),
    ('LORS DU CONTRÔLE ABSENCE DE LA CARTE BTP', 'SALARIES_ET_ENTREPRISES'),
    ('NOUVEAU SALARIE', 'SALARIES'),
    ('PRESENTATION DE LA CARTE BTP', 'SALARIES_ET_ENTREPRISES'),
    ('REFUS D’ACCES', 'SALARIES'),
    ('SALARIE / INTERVENANT / REPRESENTANT - NON SOUMIS AU CONTRÔLE', 'SALARIES'),
    ('SALARIE INSCRIT SUR LA LISTE - 1ER CONTRÔLE', 'SALARIES'),
    ('SALARIE INSCRIT SUR LA LISTE - 1ER CONTRÔLE - FIN DE MISSION', 'SALARIES'),
    ('SALARIE INSCRIT SUR LA LISTE - DÉJÀ CONTRÔLE', 'SALARIES'),
    ('SOUS-TRAITANT - NON SOUMIS AU CONTRÔLE', 'ENTREPRISES'),
    ('TRAITEMENT EN ATTENTE - ATTENTE DE COORDONNEES DE CONTACT PAR LE DONNEUR D''ORDRE', 'ENTREPRISES'),
    ('TRAITEMENT EN ATTENTE - ATTENTE DE L''ACCORD DE SOUS-TRAITANCE PAR LE DONNEUR D''ORDRE', 'ENTREPRISES');
